name: Buildlight

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - master

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: collectiveidea/buildlight@main
