name: CI

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      RUBYOPT: --enable=frozen-string-literal

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 3.1.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1
        bundler-cache: true
    - uses: actions/cache@v1

    - name: Run Tests
      run: ruby test/no_phone_test.rb
