name: CI

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUBYOPT: --enable=frozen-string-literal

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.4.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.1
        bundler-cache: true

    - name: Run Standard
      run: bundle exec standardrb

    - name: Run Tests
      run: ruby test/no_phone_test.rb
